version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
    nodejs: "20"
  jobs:
    install:
      - "asdf plugin add uv"
      - "asdf install uv latest"
      - "asdf global uv latest"
      - "uv venv $READTHEDOCS_VIRTUALENV_PATH"
      - "VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install -U -r docs/requirements.txt"
    build:
      html:
        - "python -m jupyter book build docs/ --path-output ."
        - "mkdir -p $READTHEDOCS_OUTPUT"
        - "mv _build/* $READTHEDOCS_OUTPUT"
