version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    install:
      - "python -m pip install -U -r docs/requirements.txt"
    build:
      html:
        - "python -m jupyter book build docs/ --path-output ."
        - "mkdir -p $READTHEDOCS_OUTPUT"
        - "mv _build/* $READTHEDOCS_OUTPUT"
