version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    build:
      html:
        - "jupyter-book build docs/"
        - "mkdir -p $READTHEDOCS_OUTPUT"
        - "mv _build/* $READTHEDOCS_OUTPUT"

python:
  install:
    - requirements: docs/requirements.txt
