minversion = "4"
env_list = ["py312", "py311", "py310", "py39"]
isolated_build = true
skip_missing_interpreters = true

[env_run_base]
extras = [tests]
commands = [
    [
        'pytest',
        "tests",
        "--basetemp",
        "{envtmpdir}",
        { replace = "posargs", extend = true },
    ],
]

[pytest]
script_launch_mode = "subprocess"

[gh-actions]
python = """
3.9: py39
3.10: py310
3.11: py311
3.12: py312"""
