minversion = "4"
env_list = ["py313t", "py313", "py312", "py311", "py310"]
isolated_build = true
skip_missing_interpreters = true

[env_run_base]
extras = ["tests"]
commands = [
    [
        'pytest',
        "tests",
        "--basetemp",
        "{envtmpdir}",
        { replace = "posargs", extend = true },
    ],
]

[gh-actions]
python = """
3.10: py310
3.11: py311
3.12: py312
3.13: py313
3.13t: py313t
"""
