type = "rtd"

[task]
discriminator_loss_weight = 50
embeddings_sharing = "electra"
mask_ratio = 0.15


[tuning]
batch_size = 128
betas = [0.9, 0.999]
epsilon = 1e-6
gradient_clipping = 1.0
learning_rate = 5e-4
lr_decay_steps = 1048567
warmup_steps = 1024
weight_decay = 1e-2